const std = @import("std");
const IR = @import("../lower.zig");
const Program = @import("../lower.zig").Program;

pub fn emit(program: *const Program, writer: *std.Io.Writer) !void {
    try emitFileHeader(program, writer);
    try emitStates(program, writer);
    try emitRoles(writer);
    try emitEnums(program, writer);
    try emitStructs(program, writer);
    try emitPackets(program, writer);
    try emitHandles(program, writer);
    try emitProtocol(program, writer);
}

// ── File header ───────────────────────────────────────────────────────────────

/// Emit the top of the file: generated warning, std import, and protocol
/// metadata as comptime constants.
fn emitFileHeader(ir: *const Program, writer: *std.Io.Writer) !void {
    try writer.print("// Generated by ZB2\n// Protocol: {s} v{d}\nconst std = @import(\"std\");\n\n", .{ ir.protocol.name, ir.protocol.version });
}

// ── States ────────────────────────────────────────────────────────────────────

/// Emit a `State` enum whose variants are the declared states.
/// The backing type is u32.
fn emitStates(ir: *const Program, writer: *std.Io.Writer) !void {
    try writer.print("pub const State = enum(u32) {{\n", .{});
    for (ir.states) |state| {
        try writer.print("    {s} = {},\n", .{ state.name, state.value });
    }
    try writer.print("}};\n\n", .{});
}

// ── Roles ─────────────────────────────────────────────────────────────────────

/// Emit the `Role` enum: server | client.
/// Always the same regardless of the protocol definition.
fn emitRoles(writer: *std.Io.Writer) !void {
    try writer.print(
        \\pub const Role = enum {{
        \\    server,
        \\    client,
        \\}};
        \\
        \\
    , .{});
}

// ── Enums ─────────────────────────────────────────────────────────────────────

/// Emit all enum declarations, each with a `read` and `write` method.
///
/// read  — reads the backing integer from the reader and returns the enum value
/// write — writes the backing integer of the enum value to the writer
fn emitEnums(ir: *const Program, writer: *std.Io.Writer) !void {
    for (ir.enums) |e| try emitEnum(ir, &e, writer);
}

fn emitEnum(ir: *const Program, e: *const IR.Enum, writer: *std.Io.Writer) !void {
    const backing = primitiveTypeName(e.backing);
    const endian = endianLiteral(ir.protocol.endian);

    try writer.print("pub const {s} = enum({s}) {{\n", .{ e.name, backing });
    for (e.variants) |variant| {
        try writer.print("    {s} = {},\n", .{ variant.name, variant.value });
    }
    try writer.print("\n", .{});
    try writer.print("    pub fn read(reader: *std.Io.Reader) !{s} {{\n", .{e.name});
    try writer.print("        return @enumFromInt(try reader.takeInt({s}, {s}));\n", .{ backing, endian });
    try writer.print("    }}\n\n", .{});
    try writer.print("    pub fn write(self: {s}, writer: *std.Io.Writer) !void {{\n", .{e.name});
    try writer.print("        try writer.writeInt({s}, @intFromEnum(self), {s});\n", .{ backing, endian });
    try writer.print("    }}\n", .{});
    try writer.print("}};\n\n", .{});
}

// ── Structs ───────────────────────────────────────────────────────────────────

/// Emit all struct declarations, each with a `read` and `write` method.
/// Structs are emitted before packets so packets can reference them.
///
/// read  — takes (buffer, reader); returns a fully populated struct.
///         fixed arrays use readBytesNoEof.
///         prefixed arrays slice directly into buffer, advancing the reader.
///         nested structs delegate to their own read method.
/// write — takes (writer); serializes all fields in declaration order.
fn emitStructs(ir: *const Program, writer: *std.Io.Writer) !void {
    for (ir.structs) |s| try emitStruct(ir, &s, writer);
}

fn elementTypename(t: IR.ElementType) []const u8 {
    return switch (t) {
        .enum_ref => t.enum_ref.name,
        .struct_ref => t.struct_ref.name,
        .primitive => primitiveTypeName(t.primitive),
    };
}

fn typename(t: IR.FieldType) []const u8 {
    return switch (t) {
        .primitive => primitiveTypeName(t.primitive),
        .enum_ref => t.enum_ref.name,
        .struct_ref => t.struct_ref.name,
        else => @panic("Arrays are handled in code"),
    };
}

fn prefixTypename(t: IR.PrefixType) []const u8 {
    return switch (t) {
        .u8 => "u8",
        .u16 => "u16",
        .u32 => "u32",
        .varint => @panic("varint prefix is not supported"),
    };
}

fn emitField(f: *const IR.Field, writer: *std.Io.Writer) !void {
    switch (f.type) {
        .array => |a| {
            switch (a.size) {
                .fixed => {
                    try writer.print("    {s}: [{}]{s},\n", .{ f.name, a.size.fixed, elementTypename(a.element) });
                },
                .prefix => {
                    try writer.print("    {s}: []{s},\n", .{ f.name, elementTypename(a.element) });
                },
            }
        },
        else => {
            try writer.print("    {s}: {s},\n", .{ f.name, typename(f.type) });
        },
    }
}

fn emitStruct(ir: *const Program, s: *const IR.Struct, writer: *std.Io.Writer) !void {
    // 1. emit declaration: pub const Name = struct {
    try writer.print("pub const {s} = struct {{\n", .{s.name});
    try writer.print("    const Self = @This();\n", .{});

    // 2. emit fields:      name: Type,
    for (s.fields) |f| {
        try emitField(&f, writer);
    }

    // 3. emit read method  (see emitReadMethod)
    try emitReadMethod(ir, s.fields, writer);
    // 4. emit write method (see emitWriteMethod)
    try emitWriteMethod(ir, s.fields, writer);

    try writer.print("}};\n\n", .{});
}

// ── Packets ───────────────────────────────────────────────────────────────────

/// Emit all packet declarations. Packets are structs with read/write methods
/// but are kept separate from user-defined structs in the IR and in the output.
fn emitPackets(ir: *const Program, writer: *std.Io.Writer) !void {
    for (ir.packets) |p| try emitPacket(ir, &p, writer);
}

fn emitPacket(ir: *const Program, p: *const IR.Packet, writer: *std.Io.Writer) !void {
    // 1. emit declaration: pub const Name = struct {
    try writer.print("pub const {s} = struct {{\n", .{p.name});
    try writer.print("    const Self = @This();\n", .{});

    // 2. emit fields:      name: Type,
    for (p.fields) |f| {
        try emitField(&f, writer);
    }

    // 3. emit read method  (see emitReadMethod)
    try emitReadMethod(ir, p.fields, writer);
    // 4. emit write method (see emitWriteMethod)
    try emitWriteMethod(ir, p.fields, writer);

    try writer.print("}};\n\n", .{});
}

// ── Shared read / write method emitters ───────────────────────────────────────

/// Emit a `read` method body for any struct or packet.
/// Called by both emitStruct and emitPacket.
///
/// Algorithm:
///   for each field:
///     primitive    → reader.takeInt / readBytesNoEof / readBool
///     float        → takeInt of equivalent uint width, then @bitCast
///     bool         → takeInt u8, compare != 0
///     enum_ref     → delegate to EnumName.read(reader)
///     struct_ref   → delegate to StructName.read(buffer, reader)
///     fixed array  → reader.readBytesNoEof(N)
///     prefix array → read prefix int N, slice buffer[pos..][0..N],
///                    advance reader by N bytes
fn emitReadMethod(ir: *const Program, fields: []const IR.Field, writer: *std.Io.Writer) !void {
    try writer.print("    pub fn read(reader: *std.Io.Reader) !Self {{\n", .{});
    try writer.print("        var self: Self = undefined;\n", .{});

    for (fields) |field| {
        switch (field.type) {
            .primitive => |p| switch (p) {
                .u8, .u16, .u32, .u64, .i8, .i16, .i32, .i64 => {
                    try writer.print("        self.{s} = try reader.takeInt({s}, .{s});\n", .{ field.name, @tagName(p), @tagName(ir.protocol.endian) });
                },
                .f32 => try writer.print("        self.{s} = @bitCast(try reader.takeInt(u32, .{s}));\n", .{ field.name, @tagName(ir.protocol.endian) }),
                .f64 => try writer.print("        self.{s} = @bitCast(try reader.takeInt(u64, .{s}));\n", .{ field.name, @tagName(ir.protocol.endian) }),
                .bool => try writer.print("        self.{s} = try reader.readByte() != 0;\n", .{field.name}),
                .varint => @panic("varint not supported as standalone field type"),
            },
            .enum_ref => |e| try writer.print("        self.{s} = try {s}.read(reader);\n", .{ field.name, e.name }),
            .struct_ref => |s| try writer.print("        self.{s} = try {s}.read(reader);\n", .{ field.name, s.name }),
            .array => |a| switch (a.size) {
                .fixed => |n| try emitFixedArrayRead(ir, field.name, n, a.element, writer),
                .prefix => |pt| try emitPrefixArrayRead(ir, field.name, pt, a.element, writer),
            },
        }
    }

    try writer.print("        return self;\n", .{});
    try writer.print("    }}\n", .{});
}

fn emitFixedArrayRead(ir: *const Program, name: []const u8, n: u32, element: IR.ElementType, writer: *std.Io.Writer) !void {
    switch (element) {
        .primitive => |p| switch (p) {
            .u8 => try writer.print(
                "        @memcpy(&self.{s}, try reader.take({}));\n",
                .{ name, n },
            ),
            .u16, .u32, .u64, .i8, .i16, .i32, .i64 => try writer.print(
                "        for (&self.{s}) |*_e| _e.* = try reader.takeInt({s}, .{s});\n",
                .{ name, @tagName(p), @tagName(ir.protocol.endian) },
            ),
            .f32 => try writer.print(
                "        for (&self.{s}) |*_e| _e.* = @bitCast(try reader.takeInt(u32, .{s}));\n",
                .{ name, @tagName(ir.protocol.endian) },
            ),
            .f64 => try writer.print(
                "        for (&self.{s}) |*_e| _e.* = @bitCast(try reader.takeInt(u64, .{s}));\n",
                .{ name, @tagName(ir.protocol.endian) },
            ),
            .bool, .varint => unreachable, // rejected by sema
        },
        .enum_ref => |e| try writer.print(
            "        for (&self.{s}) |*_e| _e.* = try {s}.read(reader);\n",
            .{ name, e.name },
        ),
        .struct_ref => |s| try writer.print(
            "        for (&self.{s}) |*_e| _e.* = try {s}.read(reader);\n",
            .{ name, s.name },
        ),
    }
}

/// Prefix array read: take all element bytes at once from the reader's buffer
/// (zero-copy), then decode in-place via a fixed blob reader.
///
/// For []u8 this is a straight slice — no decoding needed.
/// For []T where T has a known fixed wire size, we take N*@sizeOf(T) bytes,
/// @ptrCast the raw slice to []T, and use a blob reader to decode each element
/// into the same memory (each read consumes bytes that are then overwritten with
/// the native-endian value — safe because the read always precedes the write).
///
/// Note: struct element types must be fixed-size on the wire (no prefix-array
/// fields of their own) for the @sizeOf assumption to hold.
fn emitPrefixArrayRead(ir: *const Program, name: []const u8, pt: IR.PrefixType, element: IR.ElementType, writer: *std.Io.Writer) !void {
    // ── length prefix ────────────────────────────────────────────────────────
    if (pt == .varint) {
        try writer.print(
            \\        const {s}_len: u32 = blk: {{
            \\            var _v: u32 = 0;
            \\            var _s: u5 = 0;
            \\            while (true) {{
            \\                const _b = try reader.readByte();
            \\                _v |= @as(u32, _b & 0x7F) << _s;
            \\                if (_b & 0x80 == 0) break :blk _v;
            \\                _s += 7;
            \\            }}
            \\        }};
            \\
        , .{name});
    } else {
        try writer.print("        const {s}_len = try reader.takeInt({s}, .{s});\n", .{
            name, prefixTypename(pt), @tagName(ir.protocol.endian),
        });
    }

    // ── element reads ────────────────────────────────────────────────────────
    switch (element) {
        .primitive => |p| switch (p) {
            // []u8 — direct zero-copy slice from the reader's buffer.
            .u8 => try writer.print(
                "        self.{s} = try reader.take({s}_len);\n",
                .{ name, name },
            ),
            // []integer — take raw bytes, reinterpret in-place via blob reader.
            .u16, .u32, .u64, .i8, .i16, .i32, .i64 => {
                try writer.print("        {{\n", .{});
                try writer.print("            const _{s}_raw = try reader.take({s}_len * @sizeOf({s}));\n", .{ name, name, @tagName(p) });
                try writer.print("            self.{s} = @as([*]{s}, @ptrCast(_{s}_raw.ptr))[0..{s}_len];\n", .{ name, @tagName(p), name, name });
                try writer.print("            var _{s}_blob = std.Io.Reader.fixed(_{s}_raw);\n", .{ name, name });
                try writer.print("            for (self.{s}) |*_e| _e.* = try _{s}_blob.takeInt({s}, .{s});\n", .{ name, name, @tagName(p), @tagName(ir.protocol.endian) });
                try writer.print("        }}\n", .{});
            },
            // []f32 — raw bytes → []u32 blob → @bitCast each element.
            .f32 => {
                try writer.print("        {{\n", .{});
                try writer.print("            const _{s}_raw = try reader.take({s}_len * 4);\n", .{ name, name });
                try writer.print("            self.{s} = @as([*]f32, @ptrCast(_{s}_raw.ptr))[0..{s}_len];\n", .{ name, name, name });
                try writer.print("            var _{s}_blob = std.Io.Reader.fixed(_{s}_raw);\n", .{ name, name });
                try writer.print("            for (self.{s}) |*_e| _e.* = @bitCast(try _{s}_blob.takeInt(u32, .{s}));\n", .{ name, name, @tagName(ir.protocol.endian) });
                try writer.print("        }}\n", .{});
            },
            // []f64 — same pattern with u64.
            .f64 => {
                try writer.print("        {{\n", .{});
                try writer.print("            const _{s}_raw = try reader.take({s}_len * 8);\n", .{ name, name });
                try writer.print("            self.{s} = @as([*]f64, @ptrCast(_{s}_raw.ptr))[0..{s}_len];\n", .{ name, name, name });
                try writer.print("            var _{s}_blob = std.Io.Reader.fixed(_{s}_raw);\n", .{ name, name });
                try writer.print("            for (self.{s}) |*_e| _e.* = @bitCast(try _{s}_blob.takeInt(u64, .{s}));\n", .{ name, name, @tagName(ir.protocol.endian) });
                try writer.print("        }}\n", .{});
            },
            .bool, .varint => unreachable, // rejected by sema
        },
        // []EnumName — take bytes for the backing type, decode each in-place.
        .enum_ref => |e| {
            const backing = primitiveTypeName(e.backing);
            try writer.print("        {{\n", .{});
            try writer.print("            const _{s}_raw = try reader.take({s}_len * @sizeOf({s}));\n", .{ name, name, backing });
            try writer.print("            self.{s} = @as([*]{s}, @ptrCast(_{s}_raw.ptr))[0..{s}_len];\n", .{ name, e.name, name, name });
            try writer.print("            var _{s}_blob = std.Io.Reader.fixed(_{s}_raw);\n", .{ name, name });
            try writer.print("            for (self.{s}) |*_e| _e.* = try {s}.read(&_{s}_blob);\n", .{ name, e.name, name });
            try writer.print("        }}\n", .{});
        },
        // []StructName — take bytes assuming fixed wire size == @sizeOf, decode in-place.
        // Only valid for structs with no variable-length (prefix-array) fields.
        .struct_ref => |s| {
            try writer.print("        {{\n", .{});
            try writer.print("            const _{s}_raw = try reader.take({s}_len * @sizeOf({s}));\n", .{ name, name, s.name });
            try writer.print("            self.{s} = @as([*]{s}, @ptrCast(_{s}_raw.ptr))[0..{s}_len];\n", .{ name, s.name, name, name });
            try writer.print("            var _{s}_blob = std.Io.Reader.fixed(_{s}_raw);\n", .{ name, name });
            try writer.print("            for (self.{s}) |*_e| _e.* = try {s}.read(&_{s}_blob);\n", .{ name, s.name, name });
            try writer.print("        }}\n", .{});
        },
    }
}

/// Emit a `write` method body for any struct or packet.
/// Called by both emitStruct and emitPacket.
///
/// Algorithm:
///   for each field:
///     primitive    → writer.writeInt / writeAll / writeByte
///     float        → @bitCast to equivalent uint width, then writeInt
///     bool         → writeByte 1 or 0
///     enum_ref     → delegate to self.field.write(writer)
///     struct_ref   → delegate to self.field.write(writer)
///     fixed array  → writer.writeAll(&self.field)
///     prefix array → write prefix int (len), then writer.writeAll(self.field)
fn emitWriteMethod(ir: *const Program, fields: []const IR.Field, writer: *std.Io.Writer) !void {
    try writer.print("    pub fn write(self: *const Self, writer: *std.Io.Writer) !void {{\n", .{});

    for (fields) |field| {
        switch (field.type) {
            .enum_ref => try writer.print("        try self.{s}.write(writer);\n", .{field.name}),
            .struct_ref => try writer.print("        try self.{s}.write(writer);\n", .{field.name}),
            .primitive => |p| switch (p) {
                .u8, .u16, .u32, .u64, .i8, .i16, .i32, .i64 => try writer.print(
                    "        try writer.writeInt({s}, self.{s}, .{s});\n",
                    .{ @tagName(p), field.name, @tagName(ir.protocol.endian) },
                ),
                .f32 => try writer.print("        try writer.writeInt(u32, @bitCast(self.{s}), .{s});\n", .{ field.name, @tagName(ir.protocol.endian) }),
                .f64 => try writer.print("        try writer.writeInt(u64, @bitCast(self.{s}), .{s});\n", .{ field.name, @tagName(ir.protocol.endian) }),
                .bool => try writer.print("        try writer.writeByte(@intFromBool(self.{s}));\n", .{field.name}),
                .varint => @panic("varint not supported"),
            },
            .array => |a| switch (a.size) {
                .fixed => |n| try emitFixedArrayWrite(ir, field.name, n, a.element, writer),
                .prefix => |pt| try emitPrefixArrayWrite(ir, field.name, pt, a.element, writer),
            },
        }
    }

    try writer.print("    }}\n", .{});
}

fn emitFixedArrayWrite(ir: *const Program, name: []const u8, n: u32, element: IR.ElementType, writer: *std.Io.Writer) !void {
    _ = n;
    switch (element) {
        .primitive => |p| switch (p) {
            // [u8; N] — single bulk write.
            .u8 => try writer.print("        try writer.writeAll(&self.{s});\n", .{name}),
            .u16, .u32, .u64, .i8, .i16, .i32, .i64 => try writer.print(
                "        for (self.{s}) |_e| try writer.writeInt({s}, _e, .{s});\n",
                .{ name, @tagName(p), @tagName(ir.protocol.endian) },
            ),
            .f32 => try writer.print(
                "        for (self.{s}) |_e| try writer.writeInt(u32, @bitCast(_e), .{s});\n",
                .{ name, @tagName(ir.protocol.endian) },
            ),
            .f64 => try writer.print(
                "        for (self.{s}) |_e| try writer.writeInt(u64, @bitCast(_e), .{s});\n",
                .{ name, @tagName(ir.protocol.endian) },
            ),
            .bool, .varint => unreachable,
        },
        .enum_ref => |e| {
            _ = e;
            try writer.print("        for (self.{s}) |_e| try _e.write(writer);\n", .{name});
        },
        .struct_ref => |s| {
            _ = s;
            try writer.print("        for (self.{s}) |_e| try _e.write(writer);\n", .{name});
        },
    }
}

fn emitPrefixArrayWrite(ir: *const Program, name: []const u8, pt: IR.PrefixType, element: IR.ElementType, writer: *std.Io.Writer) !void {
    // Write the length prefix.
    try writer.print("        try writer.writeInt({s}, @intCast(self.{s}.len), .{s});\n", .{
        prefixTypename(pt), name, @tagName(ir.protocol.endian),
    });

    // Write elements.
    switch (element) {
        .primitive => |p| switch (p) {
            // []u8 — single bulk write, mirroring the zero-copy read.
            .u8 => try writer.print("        try writer.writeAll(self.{s});\n", .{name}),
            .u16, .u32, .u64, .i8, .i16, .i32, .i64 => try writer.print(
                "        for (self.{s}) |_e| try writer.writeInt({s}, _e, .{s});\n",
                .{ name, @tagName(p), @tagName(ir.protocol.endian) },
            ),
            .f32 => try writer.print(
                "        for (self.{s}) |_e| try writer.writeInt(u32, @bitCast(_e), .{s});\n",
                .{ name, @tagName(ir.protocol.endian) },
            ),
            .f64 => try writer.print(
                "        for (self.{s}) |_e| try writer.writeInt(u64, @bitCast(_e), .{s});\n",
                .{ name, @tagName(ir.protocol.endian) },
            ),
            .bool, .varint => unreachable,
        },
        .enum_ref => try writer.print("        for (self.{s}) |_e| try _e.write(writer);\n", .{name}),
        .struct_ref => try writer.print("        for (self.{s}) |_e| try _e.write(writer);\n", .{name}),
    }
}

// ── Handles ───────────────────────────────────────────────────────────────────

/// Emit the `Handles` struct — one optional function pointer per packet,
/// named on<PacketName>. Defaults to null.
fn emitHandles(ir: *const Program, writer: *std.Io.Writer) !void {
    try writer.print("pub const Handles = struct {{\n", .{});
    for (ir.packets) |packet| {
        try writer.print("    on{s}: ?*const fn(ctx: *anyopaque, packet: {s}) anyerror!void = null,\n", .{ packet.name, packet.name });
    }
    try writer.print("}};\n\n", .{});
}

// ── Protocol struct ───────────────────────────────────────────────────────────

/// Emit the `Protocol` struct: role, state, handles, ctx, init, handle_packet.
fn emitProtocol(ir: *const Program, writer: *std.Io.Writer) !void {
    // 1. emit fields: role, state, handles, ctx
    try writer.print("pub const Protocol = struct {{\n", .{});
    try writer.print("    role: Role,\n", .{});
    try writer.print("    state: State,\n", .{});
    try writer.print("    handles: Handles,\n", .{});
    try writer.print("    ctx: *anyopaque,\n", .{});
    try writer.print("    const Self = @This();\n", .{});

    // 2. emit handle_packet() (see emitHandlePacket)
    try emitHandlePacket(ir, writer);

    try writer.print("}};\n\n", .{});
}

/// Emit the `handle_packet` method body.
///
/// Algorithm:
///   switch role {
///     .server => receives packets directed at the server (direction == client | both)
///     .client => receives packets directed at the client (direction == server | both)
///   }
///   within each role arm:
///     switch state {
///       .StateName => {
///         switch id {
///           0xNN => read packet, call handle if set
///         }
///       }
///     }
fn emitHandlePacket(ir: *const Program, writer: *std.Io.Writer) !void {
    // init() ─────────────────────────────────────────────────────────────────
    try writer.print(
        \\
        \\    pub fn init(role: Role, state: State, ctx: *anyopaque) Self {{
        \\        return .{{ .role = role, .state = state, .handles = .{{}}, .ctx = ctx }};
        \\    }}
        \\
        \\
    , .{});

    // handle_packet() ────────────────────────────────────────────────────────
    try writer.print("    pub fn handle_packet(self: *Self, buffer: []u8, id: u32) anyerror!void {{\n", .{});
    try writer.print("        var reader = std.Io.Reader.fixed(buffer);\n", .{});
    try writer.print("        switch (self.role) {{\n", .{});

    // Two role arms.  Direction semantics (from the docstring):
    //   .server role — receives packets sent by the client (direction == .client | .both)
    //   .client role — receives packets sent by the server (direction == .server | .both)
    const Role = struct { tag: []const u8, dir: IR.Direction };
    const role_arms = [_]Role{
        .{ .tag = "server", .dir = .client },
        .{ .tag = "client", .dir = .server },
    };

    for (role_arms) |role| {
        try writer.print("            .{s} => switch (self.state) {{\n", .{role.tag});

        for (ir.states) |state| {
            try writer.print("                .{s} => switch (id) {{\n", .{state.name});

            for (ir.packets) |pkt| {
                // Packets belong to this state if the state name matches.
                if (!std.mem.eql(u8, pkt.state.name, state.name)) continue;
                // This role receives packets whose direction matches or is .both.
                if (pkt.direction != role.dir and pkt.direction != .both) continue;

                try writer.print("                    0x{X} => {{\n", .{pkt.id});
                try writer.print("                        const event = try {s}.read(&reader);\n", .{pkt.name});
                try writer.print("                        if (self.handles.on{s}) |pfn|\n", .{pkt.name});
                try writer.print("                            try pfn(self.ctx, event);\n", .{});
                try writer.print("                    }},\n", .{});
            }

            try writer.print("                    else => return error.UnknownPacketId,\n", .{});
            try writer.print("                }},\n", .{});
        }

        try writer.print("            }},\n", .{});
    }

    try writer.print("        }}\n", .{}); // switch role
    try writer.print("    }}\n", .{}); // handle_packet
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn primitiveTypeName(p: IR.PrimitiveType) []const u8 {
    return switch (p) {
        .u8 => "u8",
        .u16 => "u16",
        .u32 => "u32",
        .u64 => "u64",
        .i8 => "i8",
        .i16 => "i16",
        .i32 => "i32",
        .i64 => "i64",
        .f32 => "f32",
        .f64 => "f64",
        .bool => "bool",
        .varint => "varint",
    };
}

fn endianLiteral(e: IR.Endian) []const u8 {
    return switch (e) {
        .big => ".big",
        .little => ".little",
    };
}
