# This is a basic workflow to help you get started with Actions

name: ZeeBuffers

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.2.0
        with:
          version: 0.12.0

      - name: Build & Test
        run: |
          zig build -Doptimize=ReleaseSmall
          zig build -Doptimize=ReleaseSmall -Dtarget=x86_64-windows-msvc
          zig build test -Doptimize=ReleaseSmall

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: zbc-linux
          path: zig-out/bin/zbc
          if-no-files-found: error

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: zbc-windows
          path: zig-out/bin/zbc.exe
          if-no-files-found: error
